// Self-service repo onboarding config generator (docs/13 §2, §9).
// The onboarding wizard (Web UI) collects repo settings → generates a valid
// .forge/config.toml → opens a PR. This is the config-generator (pure logic,
// testable); the PR-creation reuses §8.3.

/** Inputs collected by the onboarding wizard. */
export interface OnboardingInput {
  /** Detected or user-selected language/ecosystem. */
  language: "python" | "typescript" | "node" | "go" | "other";
  /** The base image (defaults to a Chainguard image per language). */
  baseImage?: string;
  /** The repo's default branch. */
  defaultBranch?: string;
  /** Default model (defaults to the tier-2 workhorse). */
  defaultModel?: string;
  /** Sensitive paths (defaults to secrets/ + .env* + key files). */
  sensitivePaths?: string[];
  /** Egress allowlist (defaults to the language's package registry). */
  egressAllow?: string[];
}

/** Generate a valid .forge/config.toml string from wizard input (docs/13 §2). */
export function generateRepoConfig(input: OnboardingInput): string {
  const baseImage = input.baseImage ?? defaultBaseImage(input.language);
  const defaultModel = input.defaultModel ?? "claude-sonnet-4-6";
  const defaultBranch = input.defaultBranch ?? "main";
  const sensitive = input.sensitivePaths ?? [
    "secrets/**",
    ".env*",
    "*.pem",
    "*.key",
    "**/service-account*.json",
  ];
  const egress = input.egressAllow ?? defaultEgress(input.language);
  const setupScript =
    input.language === "python"
      ? "pip install -r requirements.txt"
      : "pnpm install --frozen-lockfile";

  const lines: string[] = [
    "# .forge/config.toml — generated by the Forge onboarding wizard (docs/13 §2).",
    "# Edit + commit; the control plane re-parses on push.",
    "",
    "[build]",
    `dockerfile = ".forge/Dockerfile"`,
    `setup_script = ".forge/setup.sh"`,
    `base_image = "${baseImage}"`,
    "",
    "[model]",
    `default = "${defaultModel}"`,
    `fallback_tier = "flex"`,
    "",
    "[policy]",
    `budget_limit_usd = 5.00`,
    "",
    "[paths]",
    `sensitive = [${sensitive.map((p) => `"${p}"`).join(", ")}]`,
    "",
    "[git]",
    `identity_strategy = "user"`,
    `default_branch = "${defaultBranch}"`,
    "",
    "[egress]",
    `allow = [${egress.map((h) => `"${h}"`).join(", ")}]`,
    "",
    "# [prewarm], [mcp], [credentials] — add as needed (docs/13 §2).",
  ];
  void setupScript;
  return lines.join("\n") + "\n";
}

/** The default Chainguard base image for a language (docs/08 §15). */
function defaultBaseImage(language: OnboardingInput["language"]): string {
  switch (language) {
    case "python":
      return "chainguard/python:latest";
    case "typescript":
    case "node":
      return "chainguard/node:22";
    case "go":
      return "chainguard/go:latest";
    default:
      return "chainguard/wolfi-base:latest";
  }
}

/** The default egress allowlist for a language (its package registry). */
function defaultEgress(language: OnboardingInput["language"]): string[] {
  switch (language) {
    case "python":
      return ["pypi.org:443", "api.github.com:443"];
    case "typescript":
    case "node":
      return ["registry.npmjs.org:443", "api.github.com:443"];
    case "go":
      return ["proxy.golang.org:443", "api.github.com:443"];
    default:
      return ["api.github.com:443"];
  }
}
